name: Docker Image CI

on:
  workflow_dispatch:
    inputs:
      tag:
        required: true
  schedule:
    - cron: '16 5 * * 6'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Docker meta
        id: meta_schedule
        if: github.event_name == 'schedule'
        uses: docker/metadata-action@v3
        with:
          flavor: |
            latest=true
          images: |
            ghcr.io/bkupidura/waf-modsecurity
          tags: |
            type=schedule,pattern={{date 'DDMMYYYY'}}
      -
        name: Docker meta
        id: meta_workflow_dispatch
        if: github.event_name == 'workflow_dispatch'
        uses: docker/metadata-action@v3
        with:
          flavor: |
            latest=true
          images: |
            ghcr.io/bkupidura/waf-modsecurity
          tags: |
            type=raw,value=${{ github.event.inputs.tag }}
      -
        name: Login to registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: bkupidura
          password: ${{ secrets.GITHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: ${{ steps.meta_schedule.outputs.tags || steps.meta_workflow_dispatch.outputs.tags}}
          labels: ${{ steps.meta_schedule.outputs.labels || steps.meta_workflow_dispatch.outputs.labels }}
